name: Install Action

inputs:
  tool:
    description: "Tools to install (comma-separated list)"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Action
      id: install_action
      uses: taiki-e/install-action@9ba3ac3fd006a70c6e186a683577abc1ccf0ff3a # v2.54.0
      with:
        tool: ${{ inputs.tool }}
