name: Setup Buf

inputs:
  version:
    description: "Version of the Buf CLI to use"
    required: false
  setup_only:
    description: "Setup only the buf environment, without executing other commands"
    required: false
    default: "false"

outputs:
  buf_version:
    description: "Version of the Buf CLI used."
    value: ${{ steps.setup_buf.outputs.buf_version }}
  buf_path:
    description: "Path to the Buf CLI binary."
    value: ${{ steps.setup_buf.outputs.buf_path }}

runs:
  using: "composite"
  steps:
    - name: Setup Buf
      id: setup_buf
      uses: bufbuild/buf-action@c231a1aa9281e5db706c970f468f0744a37561fd # v1.2.0
      with:
        version: ${{ inputs.version }}
        setup_only: ${{ inputs.setup_only }}
