name: Setup Buf

inputs:
  version:
    description: "Version of the Buf CLI to use"
    required: false
  setup_only:
    description: "Setup only the buf environment, without executing other commands"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Setup Buf
      id: setup_buf
      uses: bufbuild/buf-action@5150a1eef5c10b6a5cf8a69fc872f24a09473195 # v1.1.1
      with:
        version: ${{ inputs.version }}
        setup_only: ${{ inputs.setup_only }}
