name: Setup Rust Toolchain

inputs:
  components:
    description: "Comma-separated list of components to be additionally installed"
    required: false
  cache-key:
    description: "Additional cache key that can be used to further differentiate jobs"
    required: false

outputs:
  rustc-version:
    description: "Version as reported by `rustc --version`"
    value: ${{ steps.setup_rust_toolchain.outputs.rustc-version }}
  cargo-version:
    description: "Version as reported by `cargo --version`"
    value: ${{ steps.setup_rust_toolchain.outputs.cargo-version }}
  rustup-version:
    description: "Version as reported by `rustup --version`"
    value: ${{ steps.setup_rust_toolchain.outputs.rustup-version }}
  cachekey:
    description: "A short hash of the rustc version, appropriate for use as a cache key."
    value: ${{ steps.setup_rust_toolchain.outputs.cachekey }}

runs:
  using: "composite"
  steps:
    - name: Setup Rust Toolchain
      id: setup_rust_toolchain
      uses: actions-rust-lang/setup-rust-toolchain@9399c7bb15d4c7d47b27263d024f0a4978346ba4 # v1.11.0
      with:
        components: ${{ inputs.components }}
        cache-key: ${{ inputs.cache-key }}
