name: Deploy Pages

outputs:
  page_url:
    description: "URL to deployed GitHub Pages"
    value: ${{ steps.deploy_pages.outputs.page_url }}

runs:
  using: "composite"
  steps:
    - name: Deploy Pages
      id: deploy_pages
      uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
