name: "Setup Buildx"

outputs:
  name:
    description: "Builder name"
    value: ${{ steps.setup_buildx.outputs.name }}
  driver:
    description: "Builder driver"
    value: ${{ steps.setup_buildx.outputs.driver }}
  platforms:
    description: "Builder node platforms (preferred or available)"
    value: ${{ steps.setup_buildx.outputs.platforms }}
  nodes:
    description: "Builder nodes metadata"
    value: ${{ steps.setup_buildx.outputs.nodes }}

runs:
  using: "composite"
  steps:
    - name: Setup Buildx
      id: setup_buildx
      uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0
