name: Setup Node

inputs:
  node-version:
    description: "Version spec of the version to use"
    required: false
  cache:
    description: "Used to specify a package manager for caching in the default directory"
    required: false

outputs:
  cache_hit: 
    description: "A boolean value to indicate if a cache was hit."
    value: ${{ steps.setup_node.outputs.cache-hit }}
  node_version:
    description: "The installed node version."
    value: ${{ steps.setup_node.outputs.node-version }}

runs:
  using: "composite"
  steps:
    - name: Setup Node
      id: setup_node
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version: ${{ inputs.node-version }}
        cache: ${{ inputs.cache }}
