name: Setup Node

inputs:
  node-version:
    description: "Version spec of the version to use"
    required: false
  cache:
    description: "Used to specify a package manager for caching in the default directory"
    required: false

runs:
  using: "composite"
  steps:
    - name: Setup Node
      id: setup_node
      uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
      with:
        node-version: ${{ inputs.node-version }}
        cache: ${{ inputs.cache }}
