name: Configure AWS Credentials

inputs:
  aws-region:
    description: AWS Region
    required: true
  role-to-assume:
    description: The Amazon Resource Name (ARN) of the role to assume.
    required: true

runs:
  using: "composite"
  steps:
    - name: Configure AWS Credentials
      id: configure_aws_credentials
      uses: aws-actions/configure-aws-credentials@ececac1a45f3b08a01d2dd070d28d111c5fe6722 # v4.1.0
      with:
        role-to-assume: ${{ inputs.role-to-assume }}
        aws-region: ${{ inputs.aws-region }}
