name: Configure AWS Credentials

inputs:
  aws-region:
    description: AWS Region
    required: true
  role-to-assume:
    description: The Amazon Resource Name (ARN) of the role to assume.
    required: true

outputs:
  aws_account_id:
    description: "The AWS account ID for the provided credentials"
    value: ${{ steps.configure_aws_credentials.outputs.aws-account-id }}
  aws_access_key_id:
    description: "The AWS access key ID for the provided credentials"
    value: ${{ steps.configure_aws_credentials.outputs.aws-access-key-id }}
  aws_secret_access_key:
    description: "The AWS secret access key for the provided credentials"
    value: ${{ steps.configure_aws_credentials.outputs.aws-secret-access-key }}
  aws_session_token:
    description: "The AWS session token for the provided credentials"
    value: ${{ steps.configure_aws_credentials.outputs.aws-session-token }}

runs:
  using: "composite"
  steps:
    - name: Configure AWS Credentials
      id: configure_aws_credentials
      uses: aws-actions/configure-aws-credentials@b47578312673ae6fa5b5096b330d9fbac3d116df # v4.2.1
      with:
        role-to-assume: ${{ inputs.role-to-assume }}
        aws-region: ${{ inputs.aws-region }}
