name: Github Script

inputs:
  script:
    description: "The script to run"
    required: true

runs:
  using: "composite"
  steps:
    - name: Github Script
      id: github_script
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      with:
        script: ${{ inputs.script }}
