name: Amazon ECR Login

outputs:
  registry:
    description: "The URI of the ECR Private or ECR Public registry."
    value: ${{ steps.amazon_ecr_login.outputs.registry }}

runs:
  using: "composite"
  steps:
    - name: Amazon ECR Login
      id: amazon_ecr_login
      uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2.0.1
