name: Amazon ECR Login

runs:
  using: "composite"
  steps:
    - name: Amazon ECR Login
      id: amazon_ecr_login
      uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2.0.1
