name: Checkout Repository

inputs:
  repository:
    description: "The repository to checkout"
    required: false
    default: ${{ github.repository }}
  ref:
    description: "The branch, tag or SHA to checkout"
    required: false

outputs:
  ref:
    description: "The branch, tag or SHA that was checked out"
    value: ${{ steps.checkout_repository.outputs.ref }}
  commit:
    description: "The commit SHA that was checked out"
    value: ${{ steps.checkout_repository.outputs.commit }}

runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      id: checkout_repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.ref }}
        persist-credentials: false
