name: Checkout Repository

inputs:
  repository:
    description: "The repository to checkout"
    required: true
  ref:
    description: "The branch, tag or SHA to checkout"
    required: false
    default: ${{ github.event.repository.default_branch }}

runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      id: checkout_repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.ref }}
        persist-credentials: false
