name: Setup Python

inputs:
  python-version:
    description: "Version range or exact version of Python to use"
    required: false

outputs:
  python_version:
    description: "The installed Python or PyPy version. Useful when given a version range as input."
    value: ${{ steps.setup_python.outputs.python-version }}
  cache_hit:
    description: "A boolean value to indicate a cache entry was found"
    value: ${{ steps.setup_python.outputs.cache-hit }}
  python_path:
    description: "The absolute path to the Python or PyPy executable."
    value: ${{ steps.setup_python.outputs.python-path }}

runs:
  using: "composite"
  steps:
    - name: Setup Python
      id: setup_python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      with:
        python-version: ${{ env.PYTHON_VERSION }}
