name: Setup Pnpm

outputs:
  dest:
    description: "Expanded path of inputs#dest"
    value: ${{ steps.setup_pnpm.outputs.dest }}
  bin_dest:
    description: "Location of `pnpm` and `pnpx` command"
    value: ${{ steps.setup_pnpm.outputs.bin_dest }}

runs:
  using: "composite"
  steps:
    - name: Setup Pnpm
      id: setup_pnpm
      uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
