name: Configure Pages

outputs:
  base_url:
    description: "GitHub Pages site full base URL"
    value: ${{ steps.configure_pages.outputs.base_url }}
  origin:
    description: "GitHub Pages site origin"
    value: ${{ steps.configure_pages.outputs.origin }}
  host:
    description: "GitHub Pages site host"
    value: ${{ steps.configure_pages.outputs.host }}
  base_path:
    description: "GitHub Pages site full base path"
    value: ${{ steps.configure_pages.outputs.base_path }}

runs:
  using: "composite"
  steps:
    - name: Configure Pages
      id: configure_pages
      uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5.0.0
