name: Upload Pages Artifact

inputs:
  path:
    description: "Path of the directory containing the static assets"
    required: true

outputs:
  artifact_id:
    description: "The ID of the artifact that was uploaded."
    value: ${{ steps.upload_pages_artifact.outputs.artifact_id }}

runs:
  using: "composite"
  steps:
    - name: Upload Pages Artifact
      id: upload_pages_artifact
      uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3.0.1
      with:
        path: ${{ inputs.path }}
