name: "Docker Login"

inputs:
  username:
    description: "Docker username"
    required: true
  password:
    description: "Docker password"
    required: true

runs:
  using: "composite"
  steps:
    - name: Docker Login
      id: docker_login
      uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
