name: Attest Build Provenance

inputs:
  subject-name:
    description: Subject name as it should appear in the attestation
    required: true
  subject-digest:
    description: Digest of the subject for which provenance will be generated
    required: true

runs:
  using: "composite"
  steps:
    - name: Generate Artifact Attestation
      id: generate_artifact_attestation
      uses: actions/attest-build-provenance@c074443f1aee8d4aeeae555aebba3282517141b2 # v2.2.3
      with:
        subject-name: ${{ inputs.subject-name }}
        subject-digest: ${{ inputs.subject-digest }}
        push-to-registry: true
